apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "node-app.fullname" . }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ include "node-app.fullname" . }}

  template:
    metadata:
      labels:
        app: {{ include "node-app.fullname" . }}

    spec:
      containers:
        - name: {{ include "node-app.fullname" . }}
          image: {{ .Values.image.imageName }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          envFrom:
            - configMapRef:
                name: {{ include "node-app.fullname" . }}-config

          ports:
            - containerPort: {{ .Values.service.containerPort }}