apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
  namespace: production
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
      - name: my-node-app
        image: myapp:2.0
        imagePullPolicy: Never
        envFrom:
          - configMapRef:
              name: my-node-app-config
        ports:
        - containerPort: 3000