replicaCount: 1

environment: 
  PORT: "3000"
  APP_NAME: "My Node.Js App - Kubernetes"
  ENVIRONMENT: "production"

image: 
  imageName: my-node-app
  tag: "1.0"
  pullPolicy: Never

service:
  type: NodePort 
  port: 3000
  containerPort: 3000   