name: hello pipeline
on:         
 push: 

jobs: 
  hello: 
    runs-on: ubuntu-latest
    steps: 
      - name: Print Hello
        run: echo "hello"

      - name: show system info
        run: uname -a 

      - name: check nodejs version
        run: node --version
        
  